### ISSUE TITLE
Issue with local result store and docker-compose volume

### ISSUE THREAD

**Issue by vicmosin** [APSL/docker-thumbor#101]
Here is my config for docker-compose:
```
thumbor:
    image: apsl/thumbor:latest
    volumes:
      - /var/data/thumbor:/data
    environment:
      - ALLOW_UNSAFE_URL=True
      - DETECTORS=[]
      - LOADER=tc_aws.loaders.s3_loader
      - TC_AWS_LOADER_BUCKET=bucket
      - UPLOAD_ENABLED=True
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - TC_AWS_ENDPOINT='https://ams3.digitaloceanspaces.com'
      - TC_AWS_STORAGE_BUCKET=bucket
      - STORAGE=tc_aws.storages.s3_storage
      - UPLOAD_PHOTO_STORAGE=tc_aws.storages.s3_storage
      - RESULT_STORAGE=thumbor.result_storages.file_storage
      - RESULT_STORAGE_FILE_STORAGE_ROOT_PATH=/result
      - SENTRY_DSN_URL=
    networks:
      - host
```

S3 storage looks fine, loader as well. but I can't make it store results on local storage. 
I've created /var/data/thumbor and /var/data/thumbor/result manually
