### ISSUE TITLE
Issue with docker-compose

### ISSUE THREAD

**Issue by techroller** [APSL/docker-thumbor#2]
Hello,

I have been trying to use docker-compose to stand up a Thumbor server but I continue to get the following error:

```
ERROR: Validation failed, reason(s):
Service 'thumbor' configuration key 'environment' 'DETECTORS' contains ['thumbor.detectors.feature_detector', 'thumbor.detectors.face_detector'], which is an invalid type, it should be a string, number, boolean or a null
```

My docker-compose.yml file is a slightly modified version of the docker-compose-production.yml except I have added in the S3 configuration stuff.

```
thumbor:
  image: apsl/thumbor-multiprocess:latest
  volumes:
    - data:/data
    - logs:/logs
  #ports:
    #- "80:80" # thumbor port
  environment:
    ALLOW_UNSAFE_URL: 'False'
    SECURITY_KEY: ...
    DETECTORS: ['thumbor.detectors.feature_detector','thumbor.detectors.face_detector',]
    AWS_ACCESS_KEY: ...
    AWS_SECRET_KEY: ...
    STORAGE: thumbor.storages.mixed_storage
    STORAGE_BUCKET: ...
    RESULT_STORAGE_BUCKET: ...-result
    UPLOAD_PHOTO_STORAGE: thumbor_aws.storages.s3_storage
    MIXED_STORAGE_FILE_STORAGE: thumbor_aws.storages.s3_storage
    RESULT_STORAGE: thumbor_aws.result_storages.s3_storage
    REDIS_STORAGE_SERVER_HOST: redis
    REDIS_STORAGE_SERVER_PORT: 6379
    REDIS_STORAGE_SERVER_DB: 0
    REDIS_QUEUE_SERVER_HOST: redis
    REDIS_QUEUE_SERVER_PORT: 6379
    REDIS_QUEUE_SERVER_DB: 0
    MIXED_STORAGE_DETECTOR_STORAGE: thumbor.storages.redis_storage
    #SENTRY_DSN_URL: # put your sentry enpoint here
    THUMBOR_NUM_PROCESSES: 16
  links:
    - redis:redis
nginx:
  image: apsl/thumbor-nginx:latest
  links:
    - thumbor:thumbor
  volumes_from:
    - thumbor
  ports:
    - "80:80" # nginx cache port (with failover to thumbor)
  hostname: ...
remotecv:
  image: apsl/remotecv:latest
  links:
    - redis:redis
  environment:
    REDIS_HOST: redis
    REDIS_PORT: 6379
    REDIS_DATABASE: 0
redis:
  image: redis:latest
```

I am doing a simple docker-compose up.  I am probably just missing something.  Can you point me in the right direction?

Thanks!
