### ISSUE TITLE
Error using docker-compose example

### ISSUE THREAD

**Issue by chrismou** [APSL/docker-thumbor#22]
I'm trying to get a basic container running using your examples, but docker-compose if throwing errors.

This is probably a duplicate of #2, but as it's closed I figured best opening a new ticket.

The example I'm using is:

```
thumbor:
  image: apsl/thumbor:latest
  volumes:
    - data:/data
  ports:
    - "80:8000" # thumbor port
  environment:
    DETECTORS: ['thumbor.detectors.face_detector','thumbor.detectors.feature_detector',]
```

And the error is:

```
thumbor.environment.DETECTORS contains ["thumbor.detectors.face_detector", "thumbor.detectors.feature_detector"], which is an invalid type, it should be a string, number, or a null
```

docker version: 1.11.1, build 5604cbe
docker-compose version: 1.7.1, build 0a9ab35

Trying it on a newly installed, vanilla DigitalOcean Ubuntu 14.04 VPS.

If you're struggling to recreate it, could you let me know what versions of docker/docker compose you're using so I can try with those?

**Comment by eduherraiz** [comment]
Please, could you test adding a double quotes in the DETECTORS varaible?
Like this:

```
thumbor:
  image: apsl/thumbor:latest
  volumes:
    - data:/data
  ports:
    - "80:8000" # thumbor port
  environment:
    DETECTORS: "['thumbor.detectors.face_detector','thumbor.detectors.feature_detector',]"
```

This happens for the new docker-compose version.
I will modify the example!
