### ISSUE TITLE
NameError: name 'true' is not defined

### ISSUE THREAD

**Issue by fentas** [APSL/docker-thumbor#3]
Hey there,
first thanks, for this docker.
I have following docker-compose

``` yml
images:
  image: apsl/thumbor
  stdin_open: true
  tty: true
  restart: always
  environment:
    MAX_AGE: 86400
    MIN_WIDTH: 100
    MIN_HEIGHT: 100
    ALLOW_ANIMATED_GIFS: True
    AUTO_WEBP: True
    SECURITY_KEY: "LKJSAKDnmkwle2wewkl242NKnjs230kljknm"
    ALLOW_UNSAFE_URL: False
    ALLOW_OLD_URLS: False
    STORAGE_EXPIRATION_SECONDS: 7776000 #90 days
    FILE_STORAGE_ROOT_PATH: '/data/storage'
    RESULT_STORAGE_EXPIRATION_SECONDS: 2592000 #30 days
    UPLOAD_MAX_SIZE: 10240 # 10MB
    UPLOAD_ENABLED: True
    UPLOAD_PUT_ALLOWED: True
  volumes:
    - /images/:/data/storage/:rw
```

When I try to start it I get following error repentantly thrown.

``` log
11/11/2015 2:46:42 AMTraceback (most recent call last):
11/11/2015 2:46:42 AM  File "/usr/local/bin/thumbor", line 9, in <module>
11/11/2015 2:46:42 AM    load_entry_point('thumbor==5.2.1', 'console_scripts', 'thumbor')()
11/11/2015 2:46:42 AM  File "/usr/local/lib/python2.7/site-packages/thumbor/server.py", line 46, in main
11/11/2015 2:46:42 AM    config = Config.load(server_parameters.config_path, conf_name='thumbor.conf', lookup_paths=lookup_paths)
11/11/2015 2:46:42 AM  File "/usr/local/lib/python2.7/site-packages/derpconf/config.py", line 75, in load
11/11/2015 2:46:42 AM    return cls.__load_from_path(conf, path)
11/11/2015 2:46:42 AM  File "/usr/local/lib/python2.7/site-packages/derpconf/config.py", line 84, in __load_from_path
11/11/2015 2:46:42 AM    six.exec_(code, module.__dict__)
11/11/2015 2:46:42 AM  File "/usr/local/lib/python2.7/site-packages/six.py", line 699, in exec_
11/11/2015 2:46:42 AM    exec("""exec _code_ in _globs_, _locs_""")
11/11/2015 2:46:42 AM  File "<string>", line 1, in <module>
11/11/2015 2:46:42 AM  File "<string>", line 50, in <module>
11/11/2015 2:46:42 AMNameError: name 'true' is not defined
```

Hope you can help. : )
