### ISSUE TITLE
Enable webp will prevent image cached in result_storage

### ISSUE THREAD

**Issue by augustine-tran** [APSL/docker-thumbor#54]
I noticed that after enable AUTO_WEBP=True then image don't auto save to result_storage folder. Here is my docker-compose.yml config
```
thumbor:
    image: apsl/thumbor
    volumes:
      - ./stack/thumbor/.data:/data
    environment:
      - ALLOW_UNSAFE_URL=True
      - SECURITY_KEY=Cyberdyne2017
      - RESULT_STORAGE_STORES_UNSAFE=True
      - AUTO_WEBP=True
  nginx:
    image: apsl/thumbor-nginx:latest
    links:
      - thumbor:thumbor
    volumes:
      - ./stack/thumbor/.data:/data
    ports:
      - 12003:80
```

Not sure if its related to this issue [Webp from result_storage is not setting Vary header #731
](https://github.com/thumbor/thumbor/issues/731).
