### ISSUE TITLE
Cannot store image results on S3

### ISSUE THREAD

**Issue by carlos4ndre** [APSL/docker-thumbor#65]
Hi!

I'm having some issues with my result storage, it was setup to use S3 but for some reason Thumbor is not creating any post processed images on it, however the other storage for original images seems to be working just fine. 

Is there something wrong with my docker-compose configuration? Here it follows:

```
  thumbor:
    image: apsl/thumbor:6.0.1
    restart: always
    ports:
      - "8888:8000" # thumbor port
    environment:
      SECURITY_KEY: ".............."
      VIRTUAL_HOST: thumbor.docker
      STORAGE: "tc_aws.storages.s3_storage"
      RESULT_STORAGE: "tc_aws.result_storages.s3_storage"
      TC_AWS_STORAGE_BUCKET: "test"
      TC_AWS_STORAGE_ROOT_PATH: "/thumbor/storage"
      TC_AWS_RESULT_STORAGE_BUCKET: "test"
      TC_AWS_RESULT_STORAGE_ROOT_PATH: "/thumbor/result_storage"
      AWS_ACCESS_KEY_ID: ".............."
      AWS_SECRET_ACCESS_KEY: ".............."
```
