### ISSUE TITLE
Problem with storing image results on s3

### ISSUE THREAD

**Issue by gansbrest** [APSL/docker-thumbor#73]
First of all, thanks for the great easy to use container.

At the moment I try to set it up so Thumbor results are stored in s3 but storage is still filesystem (with mounted volume), so each thumbor process/container would be able to use same originals to generate presets within same server. 

I didn't dive too deeply into multi process setup, but that's how I envision it at least. Is it a good idea, or should I store originals on s3 as well? My source images are aleady on s3, so it's kind of strange to load from s3, then save to s3 storage.. Maybe I should disable storage altogether, but I figured that while I have disk space on my VPS, why not use it for storage, speed things up a bit. Would be curious to know what you would recommend.

Anyways, here is how my docker-compose looks at the moment:

````
version: '2'
services:
  thumbor:
    image: apsl/thumbor:latest
    volumes:
      - ./data:/data
      - ./logs:/logs
    ports:
      - "8888:8000" # thumbor port
    environment:
      - DETECTORS=['thumbor.detectors.feature_detector','thumbor.detectors.face_detector']
      - AWS_ACCESS_KEY_ID=XXX
      - AWS_SECRET_ACCESS_KEY=XXXX
      - SECURITY_KEY=XXX
      - ALLOW_UNSAFE_URL=True
      - TC_AWS_REGION=eu-west-2
      - TC_AWS_RESULT_STORAGE_BUCKET=XXX-thumbor-cache
      - TC_AWS_ALLOWED_BUCKETS=['XXX-thumbor-cache']
      - RESULT_STORAGE_STORES_UNSAFE=True
      - RESULT_STORAGE=tc_aws.result_storages.s3_storage
    networks:
      - app
volumes:
  data:
    driver: local
  logs:
    driver: local
networks:
  app:
    driver: bridge
````
No matter what I do no results gets stored on s3. If I change it to `RESULT_STORAGE=thumbor.result_storages.file_storage` it stores locally just fine.. so something with s3 plugin seems like. 

I tried to grant all permissions to s3 for the user just to rule out perm issue but still nothing..

Running out of ideas.. Is there a way I could debug it somehow, enable logging or something that could show me some errors during upload attempts ( at the moment there is nothing in the compose console besides thumbor_1 | 2017-04-12 00:31:33 thumbor:WARNING URL does not have hash or unsafe, or has both: /favicon.ico )

Seem to be similar to https://github.com/APSL/docker-thumbor/issues/65 but I'm already on the latest version and all config options seem to be there. 

Please advice.

**Comment by gansbrest** [comment]
Forgot to mention steps to reproduce, I just basically do:
`docker-compose up` and then in my browser `http://localhost:8888/unsafe/300x300/http://upload.wikimedia.org/wikipedia/commons/2/22/Turkish_Van_Cat.jpg` and nothing gets saved in s3 results ( it seems like it's running without results storing with my current config )

**Comment by eduherraiz** [comment]
I will review your case in a few days. Maybe the fix in #65 is not working properly.

I recommend you use thumbor storing the result_storage in local filesystem. Uploading again result_storage to s3 will be a performance problem, note the image will be served by thumbor and they have to download it again in every request.

What it's the principal problem now with local result_storage? Scale up:

1. If you want multiple thumbor processes in a different hosts every one have their own result_storage cache. It's not perfect because you have to resize the image for every host.

2. If you have multiple processes in the same host (thumbor + volumes or thumbor-multiprocess), you can be in trouble with the disk space. Thumbor's cache is so bad limiting the disk size and not purge old images. We are dealing with this using a cron jobs deleting old images in result_storage, but it's not the correct way.

The problem 1 could be mitigated with network disks solutions, like I said, result_storage in s3 seems not a good idea. To solve this problems I'm thinking in a good cache layer for thumbor in a separated docker image, using a Varnish service, and not use result_storage anymore, but I need some time to develop it.

Another practical solution by the moment could be use a CDN service for thumbor, and not use result storage.

**Comment by gansbrest** [comment]
Thanks a lot for your suggestions, decided to go with local disks for both storage and results for now.

We do use CDN on top of thumbor, but I could not find a way to disable results generation `thumbor.result_storages.no_storage` didn't work.

At the moment we use simple NFS mount with 2 thumbor VPS servers, will test if that will hold up. 

Now I'm trying to work out a strategy for storage and results cleanup. You mentioned that you use cron ( do you mind sharing it? ) but it's not the correct way. Why? And what's the correct way, as I'm sure I'll run out of storage without clearing old stuff..

I noticed 2 env variables in the docs `STORAGE_EXPIRATION_SECONDS` and `RESULT_STORAGE_EXPIRATION_SECONDS` - are those not working (can I rely on them)? How are those implemented?

**Comment by gansbrest** [comment]
@eduherraiz I thought you might miss my reply because I forgot to mention.. If you have couple mins to spare, could you share your cron that u use for purging images to free space? Thanks

**Comment by kkopachev** [comment]
```yaml
version: '2.0'
services:
  nginx:
    build:
      context: ./nginx
    links:
      - thumbor:thumbor
    ports:
      - 8080:80
  thumbor:
    image: apsl/thumbor:latest
    environment:
      ALLOW_ANIMATED_GIFS: 'True'
      ALLOW_UNSAFE_URL: 'True'
      AUTO_WEBP: 'True'
      AWS_ACCESS_KEY_ID: XYZ
      AWS_SECRET_ACCESS_KEY: XYZ
      LOADER: tc_aws.loaders.s3_loader
      RESULT_STORAGE: 'tc_aws.result_storages.s3_storage'
      SECURITY_KEY: '0123456789'
      STORAGE: thumbor.storages.no_storage
      TC_AWS_ENABLE_HTTP_LOADER: 'True'
      TC_AWS_LOADER_BUCKET: my-site-assets-bucket
      TC_AWS_LOADER_ROOT_PATH: files
      TC_AWS_REGION: us-east-1
      TC_AWS_RESULT_STORAGE_BUCKET: thumbor-results
      TC_AWS_RESULT_STORAGE_ROOT_PATH: results
      THUMBOR_NUM_PROCESSES: 16
      USE_GIFSICLE_ENGINE: 'True'
      WEBP_QUALITY: 85
```
That should load originals from s3 and save results on s3 (another bucket). No local storage of originals.
