### ISSUE TITLE
Post aways returning 415 Unsupported Media Type

### ISSUE THREAD

**Issue by dflourusso** [APSL/docker-thumbor#88]
I'm trying _POST_ many images of diferent types but it aways returns the 415 code.

`curl -i -H "Content-Type: image/jpeg" -H "Slug: photo.jpg" -X POST http://0.0.0.0:8000/image --data "./image.jpg`

What can i do?

**Comment by lenzls** [comment]
I kind of have the same problem.

What I simply did:

docker-compose:
```
thumbor:
    image: apsl/thumbor:6.4.2
    restart: always
    volumes:
      - ./thumbor-data:/data
    ports:
      - 8001:8000
    environment:
      UPLOAD_ENABLED: 1
```

then on the command line:

```
$ curl -i -H "Content-Type: image/jpeg" -H "Slug: photo.jpg" -XPOST http://localhost:8001/image --data-binary "~/images/test.jpg"
HTTP/1.1 415 Unsupported Media Type
Date: Wed, 30 May 2018 16:54:59 GMT
Content-Length: 0
Content-Type: text/html; charset=UTF-8
Server: TornadoServer/4.5.3
```

"uploading via browser" when accessing the url 
```
http://localhost:8001/unsafe/300x200/https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Wappen_Rollshausen.svg/859px-Wappen_Rollshausen.svg.png
```
 works as expected. So I see a cropped verison in the browser and in my `thumbor-data/storage` folder I get a copy of the original image.


Edit: it's the same behaviour when uploading via form:
`curl -i -XPOST http://localhost:8001/image        -F "media=~/images/test.jpg;type=image/jpeg;filename=croco.jpg"`
